name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
      types: [opened, labeled, reopened, synchronize]

  push:
    branches:
    - "trunk-*"

  workflow_dispatch:

jobs:
  start_action_runners:
    name: Start
    uses: glotzerlab/jetstream2-admin/.github/workflows/start.yaml@98f840ba341f72bf412100f2180d38c06e792b84 # v1.3.1
    secrets: inherit

  typical:
    name: "${{ join(matrix.config, '') }}"
    needs: start_action_runners
    uses: ./.github/workflows/build_and_test.yaml
    with:
      compiler_family: ${{ matrix.config[0] }}
      compiler_version: ${{ matrix.config[1] }}
      python: ${{ matrix.config[3] }}
      config: ${{ join(matrix.config, '_') }}

      # Use self-hosted runners or fall back to GitHub hosted runners when self-hosted are offline.
      build_runner: ${{ needs.start_action_runners.outputs.active != '0' && '["self-hosted","jetstream2","CPU"]' || toJson('ubuntu-24.04') }}

      # Default to false when unset
      validate: ${{ matrix.validate && 'true' || 'false'}}

      release: false

    strategy:
      fail-fast: false
      matrix:
        include:
        - config: [clang, 18, -py, 312, -mpi, -tbb]
          validate: true

        - config: [gcc, 14, -py, 312]
          validate: true

        - config: [gcc, 14, -py, 312, -nomd]
        - config: [gcc, 14, -py, 312, -nohpmc]
        - config: [gcc, 14, -py, 312, -nomd, -nohpmc]
        - config: [gcc, 10, -py, 39, -mpi, -tbb]

        - config: [cuda, 125, -py, 312, -mpi]
          validate: true

        - config: [cuda, 125, -py, 312]
          validate: true

        - config: [cuda, 125, -py, 312, -mpi, -debug]


  release:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release') }}
    name: "${{ join(matrix.config, '') }}"
    needs: start_action_runners
    uses: ./.github/workflows/build_and_test.yaml
    with:
      compiler_family: ${{ matrix.config[0] }}
      compiler_version: ${{ matrix.config[1] }}
      python: ${{ matrix.config[3] }}
      config: ${{ join(matrix.config, '_') }}

      # Use self-hosted runners or fall back to GitHub hosted runners when self-hosted are offline.
      build_runner: ${{ needs.start_action_runners.outputs.active != '0' && '["self-hosted","jetstream2","CPU"]' || toJson('ubuntu-24.04') }}

      # Default to false when unset
      validate: ${{ matrix.validate && 'true' || 'false'}}

      release: true

    strategy:
      fail-fast: false
      matrix:
        include:
        - config: [clang, 17, -py, 312, -mpi, -tbb]
        - config: [clang, 16, -py, 312, -mpi, -tbb]
        - config: [clang, 15, -py, 311, -mpi, -tbb]
        - config: [clang, 14, -py, 310, -mpi, -tbb]
        - config: [clang, 13, -py, 39, -mpi, -tbb]
        - config: [gcc, 13, -py, 312, -mpi, -tbb]
        - config: [gcc, 12, -py, 311, -mpi, -tbb]
        - config: [gcc, 11, -py, 310, -mpi, -tbb]
        - config: [gcc, 10, -py, 310, -mpi, -tbb]

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.12"
    - name: Setup uv
      uses: glotzerlab/workflows/setup-uv@5cfac9da9cb78e16ae97a9119b6fd13c1c2d6f5e # 0.1.0
    - name: Install dependencies
      run: uv pip install -r sphinx-doc/requirements.txt --system
    - name: Install tools
      run: sudo apt-get install pandoc
    - name: Build Sphinx Docs
      run: sphinx-build -b html sphinx-doc doc_build
    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v1
      with:
        args: -n --exclude-path hoomd/extern --exclude https://glotzerlab.engin.umich.edu doi.org gitlab.com -- './**/*.md' './**/*.html' './**/*.rst'
        fail: true
        

  tests_complete:
    name: Unit test
    if: always()
    needs: [typical]
    runs-on: ubuntu-24.04

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
